name: shopping_cart
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  http: ^1.2.2
  logging: ^1.2.0
  provider: ^6.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo2.png
  android: true
  ios: true 

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  remove_alpha_ios: true 

flutter:
  uses-material-design: true
